language: node_js

node_js:
  - "12"

sudo: required

services:
  - docker

script: 
  - export POSTGRES_USERNAME=postgres
  - export POSTGRES_PASSWORD=password
  - export POSTGRES_HOST=tharwatdb.cyawlht28rc7.us-east-2.rds.amazonaws.com
  - export POSTGRES_DB=postgres
  - export AWS_BUCKET=arn:aws:s3:::udagrambucket02
  - export AWS_REGION=us-east-2
  - export AWS_PROFILE=default
  - export JWT_SECRET=testing
  - export URL=http://localhost:8100
  - docker-compose -f docker-compose-build.yaml build --parallel
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push tharwat101/udagram-frontend:v1
  - docker push tharwat101/udagram-api-feed:latest
  - docker push tharwat101/udagram-api-user:latest
  - docker push tharwat101/reverseproxy:latest
