apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-frontend-deployment
  labels:
    service: udagram-frontend-service
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udagram-frontend-service
  template:
    metadata:
      labels:
        service: udagram-frontend-service
    spec:
      containers:
      - name: udagram-frontend
        image: tharwat101/udagram-frontend:v1
        ports:
          - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m" 
        env:
          - name: POSTGRES_USERNAME
            valueFrom:
              configMapKeyRef:
                name: udagram-env
                key: POSTGRES_USERNAME

          - name: POSTGRES_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: udagram-env
                key: POSTGRES_PASSWORD

          - name: POSTGRES_HOST
            valueFrom:
              configMapKeyRef:
                name: udagram-env
                key: POSTGRES_HOST

          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: udagram-env
                key: POSTGRES_DB

          - name: AWS_BUCKET
            valueFrom:
              configMapKeyRef:
                name: udagram-env
                key: AWS_BUCKET

          - name: AWS_REGION
            valueFrom:
              configMapKeyRef:
                name: udagram-env
                key: AWS_REGION

          - name: AWS_PROFILE
            valueFrom:
              configMapKeyRef:
                name: udagram-env
                key: AWS_PROFILE
          
          - name: JWT_SECRET
            valueFrom:
              configMapKeyRef:
                name: udagram-env
                key: JWT_SECRET

          - name: URL
            valueFrom:
              configMapKeyRef:
                name: udagram-env
                key: URL
